services:

  database:
    image: mysql:8.0
    container_name: donaton-db
    environment:
      - MYSQL_DATABASE=db_donaton
      - MYSQL_ROOT_PASSWORD=root 
    networks:
      - api-conection
    ports:
      - "3307:3306"

  api-gateway:
    build: 
      context: .
      dockerfile: Dockerfile
      container_name: donaton-api-gateway
    ports:
      - "8080:8080"
    environment:
      - LOGISTICA_API_URI=http://logistica-service:3001
      - DONACIONES_API_URI=http://donaciones-service:3002
      - NECESIDADES_API_URI=http://necesidades-service:3003
    networks:
      - api-conection


networks:
  api-conection:
    external: true
    name: api-conection