server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: logistica-api
          uri: http://logistica-service:3001
          predicates:
            - Path=/logistica/**
          filters:
            - StripPrefix=1

        - id: donaciones-api
          uri: http://donaciones-service:3002
          predicates:
            - Path=/donaciones/**
          filters:
            - StripPrefix=1

        - id: necesidades-api
          uri: http://necesidades-service:3003
          predicates:
            - Path=/necesidades/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    gateway:
      enabled: true