spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: logistica-service
          uri: http://logistica-service:3001
          predicates:
            - Path=/logistica/**
          filters:
            - StripPrefix=1

        - id: donacion-service
          uri: http://donacion-service:3002
          predicates:
            - Path=/donacion/**
          filters:
            - StripPrefix=1

        - id: necesidades-service
          uri: http://necesidades-service:3003
          predicates:
            - Path=/necesidades/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: "*"