spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

      routes:
        - id: logistica-service
          uri: ${LOGISTICA_API_URI}
          predicates:
            - Path=/logistica/**
          filters:
            - StripPrefix=1

        - id: donacion-service
          uri: ${DONACIONES_API_URI}
          predicates:
            - Path=/donacion/**
          filters:
            - StripPrefix=1

        - id: necesidades-service
          uri: ${NECESIDADES_API_URI}
          predicates:
            - Path=/necesidades/**
          filters:
            - StripPrefix=1

        - id: need-node-service
          uri: ${NEED_NODE_API_URI}
          predicates:
            - Path=/need-node/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: "*"